services:
  - type: web
    name: feedback
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false && blitz prisma migrate deploy --preview-feature && blitz build
    startCommand: blitz start --production
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: feedback-db
          property: connectionString
databases:
  - name: feedback-db
    plan: starter
